# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "PayForMe.xcodeproj") 
    build_app(scheme: "PayForMe")
    upload_to_testflight
  end

  lane :icon do
    appicon(
      appicon_devices: [:iphone, :ipad, :ios_marketing],
      appicon_path: 'PayForMe/Assets.xcassets'
    )
  end

  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end

  lane :githubshots do
    capture_screenshots(
      dark_mode: true,
      output_directory: "screenshots/darkmode"
    )
    capture_screenshots(
      dark_mode: false,
      clear_previous_screenshots: false,
      output_directory: "screenshots/lightmode"
    )
    frameit
  end

  lane :deliver do
    increment_build_number(xcodeproj: "PayForMe.xcodeproj") 
    build_app(scheme: "PayForMe")
    capture_screenshots
    upload_to_app_store
  end
end
